# Generated by Django 4.1.5 on 2023-01-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='countryOrigin',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
